### ISSUE TITLE
The generated XML file can be invalid

### ISSUE THREAD

**Issue by Hagendorn** [boxuk/jslint-jenkins-plugin#2]
When the JSLint error message contains a "&" or "<" char the generated XML file is invalid. 

For example when JSLint finds an issue which creates one of these error messages:
- "Unexpected use of '&'." 
- "Unexpected use of '<<'."

An invalid xml file is created:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="1.3.3">
 <file name="/var/lib/jenkins/jobs/test/workspace/test.js">
  <error line="38" column="56" severity="error" message="Unexpected use of '&'." source="jslint"/>
  <error line="38" column="64" severity="error" message="Unexpected use of '<<'." source="jslint"/>
 </file>
</checkstyle>
```

The chars "<" and "&" are strictly illegal in XML these should be replaced with "&lt;" and "&amp;"

**Comment by gavD** [comment]
Many thanks, I will attempt to get a patch in for this in the next 24 hours - hopefully tomorrow I'll have a change to look at this

**Comment by Hagendorn** [comment]
That would be great! Thanks!

**Comment by gavD** [comment]
This should now be working as of ef857c933a73fc7b2ecdcb60c94ce7b8e8a372b3 - please update to HEAD. I'm still working on #1 - I still cannot reproduce it unfortunately
