### ISSUE TITLE
JSLint and globals

### ISSUE THREAD

**Issue by cexbrayat** [boxuk/jslint-jenkins-plugin#3]
It appears you can't have a space between /\* and globals  in the directive declaration, so the sample in the [README](https://github.com/boxuk/jslint-jenkins-plugin/blob/master/README.md#using-this-plugin) is a little misleading

```
/* globals foo, bar */
```

should be

```
/*globals foo, bar */
```

Except that, works great, thanks for your job!

**Comment by gavD** [comment]
Thanks, this has been fixed in 4086e86 !
