### ISSUE TITLE
Support "predef" config option

### ISSUE THREAD

**Issue by craigmarvelley** [boxuk/jslint-jenkins-plugin#5]
See http://www.jslint.com/lint.html#options - support for the `predef` option would be nice, as in some situations (like RequireJS modules) the same global variables are used in each file.

**Comment by gavD** [comment]
Done. I'll upload shortly.

**Comment by gavD** [comment]
This has been installed on our Jenkins instance, I've written up a brief blog item and sent it to you as well. If this is stable, we'll release tomorrow.
