### ISSUE TITLE
java.io.FileNotFoundException on Windows Server 2008 R2

### ISSUE THREAD

**Issue by mamaximov** [boxuk/jslint-jenkins-plugin#7]
On Windows platform, file paths calculated in not quite right way. Here is the console log:

[JSLint] Ready
[JSLint] calling jslint with args[-DxmlOutput=c:\projectnamegoeshere\ci\trunk\Source/jslint.xml]
[JSLint] IO Error java.io.FileNotFoundException: file:\C:\Program Files (x86)\Jenkins\plugins\jslint\WEB-INF\classes\com\boxuk\jenkins\jslint\JSLintBuilder\jslint.js (The filename, directory name, or volume label syntax is incorrect)
[JSLint] Complete

**Comment by gavD** [comment]
Please could you tell me if the file exists on your machine?
Can you confirm you are using 0.7.7?

I thought that PR #6 would fix it; I don't have a Windows machine to test on.

**Comment by mamaximov** [comment]
Yes, I confirm that I''ve updated my plugin 0.7.7. I'll provide you a gist in java with tests on file.exists() so you can change the paths. I also recomend you to calculate paths in this way: File file = new FIle(dir, "somefile.ext");

**Comment by mamaximov** [comment]
done. https://gist.github.com/mamaximov/5408038
So could you try to calculate the paths in this way: new FIle(dir, "jslint.js") ?
P.S. Updated the gist

**Comment by gavD** [comment]
OK, I got the deploy to work and version 0.8.0 is released. It'll be on the Jenkins update centre in 6 hours or so but if you can't wait that long take a look at http://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/jslint/0.8.0/

Please test. If this doesn't work then I'm sorry but I give up - I simply don't have the tools for Windows development - someone else will have to submit a PR.

**Comment by mamaximov** [comment]
THAT IS AMAZING! IT WORKS! I really wonder how quickly the issue has been fixed. Thanks you from all .NET community, I really appreciate your help!
