### ISSUE TITLE
IO Error java.io.FileNotFoundException

### ISSUE THREAD

**Issue by hallja** [boxuk/jslint-jenkins-plugin#8]
Hi,

This looks similar to a previous issue, but after upgrading our Jenkins installation we are now getting the following error with the jslint-jenkins-plugin:

[JSLint] IO Error java.io.FileNotFoundException: jar:\C:\Program Files (x86)\Jenkins\plugins\jslint\WEB-INF\lib\classes.jar!\com\boxuk\jenkins\jslint\JSLintBuilder\jslint.js (The filename, directory name, or volume label syntax is incorrect)

I have checked on the server and the C:\Program Files (x86)\Jenkins\plugins\jslint\WEB-INF\lib\classes.jar is present.

We are running Jenkins v1.520 on Windows Server 2008 R2, using version 0.8.0 of the plugin.

Any assistance would be greatly appreciated.

**Comment by psliwa** [comment]
I have exactly the same issue on debian server. Jenkins version: 1.519, plugin version: 0.8.0

**Comment by solarvm** [comment]
same on ubuntu server
Jenkins: 1.520
plugin: 0.8.0
Error msg:
[JSLint] IO Error java.io.FileNotFoundException: jar:/var/lib/jenkins/plugins/jslint/WEB-INF/lib/classes.jar!/com/boxuk/jenkins/jslint/JSLintBuilder/jslint.js (No such file or directory)

**Comment by gavD** [comment]
OK, thanks for the report. Seems something's changed in Jenkins. I can't do a whole lot about Windows - I don't have any Windows gear to test on (which was a flipping nightmare with #7). It might be a few days before I can look at this so if anyone has time to fix and submit a PR, I'd be hugely grateful.

thanks,
- Gav

**Comment by jamiegood** [comment]
Hi Guys 
Same error here, just after upgrading to Jenkins 1.519 on centos

thanks
Jamie

**Comment by paazmaya** [comment]
Same trouble, with the latest Jenkins and this plugin. In Windows 8.

**Comment by ccorneli** [comment]
Same issue after upgrading Jenkins to 1.521 on Linux.
(We were already using .8 of jslint plugin with version 1.4x of Jenkins which didn't give the error before the upgrade)

[JSLint] IO Error java.io.FileNotFoundException: <Jenkins Home>/.jenkins/plugins/jslint/WEB-INF/lib/classes.jar!/com/boxuk/jenkins/jslint/JSLintBuilder/jslint.js (No such file or directory)
[JSLint] Complete

**Comment by impacmp** [comment]
Same issue here under macOSX, jenkins 1.519 newest lint plugin:
IO Error java.io.FileNotFoundException: /.jenkins/plugins/jslint/WEB-INF/lib/classes.jar ! /com/boxuk/jenkins/jslint/JSLintBuilder/jslint.js (No such file or directory)

Any fixes in sight?

**Comment by gavD** [comment]
I'm extremely busy, I don't have time to look into this at the moment.

If anybody can submit a pull request, I'll happily review it.

Please note that I cannot test on Windows.

**Comment by gavD** [comment]
I've had a very quick look and it seems that this method of opening a file inside a jar doesn't work any more. In my case:
/home/gavin/.jenkins/plugins/jslint/WEB-INF/lib/classes.jar!/com/boxuk/jenkins/jslint/JSLintBuilder/jslint.js

I have no idea why this might be; it really would be great if someone could submit a pull request to resolve this...

**Comment by gavD** [comment]
Via @squiddon , this would seem to be related https://issues.jenkins-ci.org/browse/JENKINS-18415

**Comment by gavD** [comment]
... which would suggest that the changes in https://github.com/jenkinsci/shiningpanda-plugin/commit/e77a484919239bbf3b6e913aa2b1dbde0fa81b64 might be transferable? If anyone PLEASE has time?

**Comment by gavD** [comment]
I've just committed something that fixes it for me on Ubuntu. I do not have Windows hardware to test on. If it doesn't work on Windows (see #7) then I'm afraid someone needs to fix it properly because I'm just not in a position where I can do that.

I'm doing a release now.

**Comment by hallja** [comment]
Just to confirm the issue has been fixed when running v0.8.2 of the plug-in on Windows Server 2008 R2.

Thanks!

**Comment by gavD** [comment]
Fantastic, thanks for letting me know @hallja - what a relief! :-)
